import SwiftUI

struct MapsView: View {
    @EnvironmentObject private var store: OfflineStore
    @State private var search = ""
    @State private var showingAdd = false
    var places: [SavedPlace] { search.isEmpty ? store.savedPlaces : store.savedPlaces.filter { $0.name.localizedCaseInsensitiveContains(search) } }
    var body: some View { NavigationStack { ScrollView { VStack(alignment: .leading, spacing: 18) { GlassCard { VStack(alignment: .leading, spacing: 8) { Label("Offline map viewer", systemImage: "map").font(.headline); Text("Saved places and locally stored map data remain available without a network. Online map tiles are not used here.").font(.caption).foregroundStyle(.secondary); Button("Add saved place") { showingAdd = true }.buttonStyle(.borderedProminent) } }; SectionTitle(title: "Saved places", action: "\(places.count)"); if places.isEmpty { ContentUnavailableView("No saved places", systemImage: "mappin.and.ellipse", description: Text("Store a place locally for quick offline reference.")) } else { ForEach(places) { place in GlassCard { HStack { Image(systemName: place.isFavorite ? "star.fill" : "mappin.circle.fill").foregroundStyle(place.isFavorite ? .yellow : Color.otBlue); VStack(alignment: .leading) { Text(place.name).font(.headline); Text(place.detail).font(.caption).foregroundStyle(.secondary) }; Spacer(); Button(role: .destructive) { store.removePlace(place) } label: { Image(systemName: "trash") }.accessibilityLabel("Delete \(place.name)") } } } } }.padding() }.background(Color.otInk.ignoresSafeArea()).navigationTitle("Maps").searchable(text: $search, prompt: "Search saved places").sheet(isPresented: $showingAdd) { AddPlaceView { store.addPlace($0) } } } }
}

struct AddPlaceView: View { @Environment(\.dismiss) private var dismiss; @State private var name = ""; @State private var detail = ""; let save: (SavedPlace) -> Void; var body: some View { NavigationStack { Form { TextField("Place name", text: $name); TextField("City or description", text: $detail) }.navigationTitle("Save place").toolbar { ToolbarItem(placement: .cancellationAction) { Button("Cancel") { dismiss() } }; ToolbarItem(placement: .confirmationAction) { Button("Save") { save(SavedPlace(name: name.isEmpty ? "Unnamed place" : name, detail: detail.isEmpty ? "Saved offline" : detail, latitude: 0, longitude: 0)); dismiss() }.disabled(name.isEmpty) } } } } }
